name: CI

on: [push, pull_request]

jobs:
  test:
    name: test
    runs-on: ubuntu-20.04

    steps:
      - {name: sys,shell: bash,run: 'echo "$(whoami) on $(uname -a)"; echo "::group::sudo"; sudo -lU "$(whoami)"&&echo $?||echo $?; echo "::group::env"; set -o posix; set|sort'}
      - {name: php,shell: bash,run: 'printf "::group::"; php --version ; php -i|grep -i yaml||:; echo "::endgroup::"; printf "::group::"; php -i|grep ''\$_ENV\|\$_SERVER''||:; echo "::endgroup::"'}
      - uses: actions/checkout@v3
      - run: test/shell.sh
      - name: test action
        uses: ./.
        with:
          file: test/.travis.yml

      - name: project .travis.yml action
        uses: ./.
        with:
          allow-failure: true

      - name: universal install script .travis.yml action
        uses: ./.
        with:
          allow-failure: true
          file: test/file/universal-install-script.travis.yml

      - name: plan run action
        uses: ./extra/plan
        with:
          file: test/file/universal-install-script.travis.yml

      - name: plan run action (project default .travis.yml)
        uses: ./extra/plan

      - name: plan run action - test/.travis.yml
        uses: ./extra/plan
        with:
          run-job: root
          file: test/.travis.yml

      - name: plan run action - test/.travis.yml (by env.TRAVIS_YAML_FILE)
        uses: ./extra/plan
        with:
          run-job: root
        env:
          TRAVIS_YAML_FILE: test/.travis.yml

      - name: plan run action - build-stages.travis.yml
        uses: ./extra/plan
        with:
          file: test/file/build-stages.travis.yml

      - name: plan run action - php-cs-fixer.travis.yml
        uses: ./extra/plan
        with:
          file: test/file/php-cs-fixer.travis.yml

  error:
    name: allow failure
    runs-on: ubuntu-20.04
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - id: self-error
        uses: ./.
        with:
          allow-failure: true

      - if: ${{ success() }}
        shell: bash
        run: |
          test "${{ steps.self-error.outputs.outcome }}" = "failure"
          test "${{ steps.self-error.outputs.test-result }}" = "1"

  try-machine:
    name: run on ${{ matrix.machine }}
    runs-on: ${{ matrix.machine }}
    needs: test
    continue-on-error: ${{ matrix.experimental }}

    strategy:
      fail-fast: false
      matrix:
        machine:
          - ubuntu-20.04
          - ubuntu-22.04
          - macos-11
          - macos-12
          - windows-2019
          - windows-2022
        experimental: [false]

    steps:
      - {name: sys,shell: bash,run: 'echo "$(whoami) on $(uname -a)"; echo "::group::sudo"; sudo -lU "$(whoami)"&&echo $?||echo $?; echo "::group::env"; set -o posix; set|sort'}
      - {name: php,shell: bash,run: 'printf "::group::"; php --version ; php -i|grep -i yaml||:; echo "::endgroup::"; printf "::group::"; php -i|grep ''\$_ENV\|\$_SERVER''||:; echo "::endgroup::"'}
      - uses: actions/checkout@v3
      - name: run .travis.yml
        uses: ./.
        env:
          TRAVIS_ALLOW_FAILURE: true

      - name: plan run action
        uses: ./extra/plan
        with:
          file: test/file/universal-install-script.travis.yml

      - name: plan run action - test/.travis.yml
        uses: ./extra/plan
        with:
          file: test/.travis.yml

      - name: plan run action - build-stages.travis.yml
        uses: ./extra/plan
        with:
          file: test/file/build-stages.travis.yml

      - name: plan run action - php-cs-fixer.travis.yml
        uses: ./extra/plan
        with:
          file: test/file/php-cs-fixer.travis.yml
